### ISSUE TITLE
Error: Decoding error on OPEN_ORDER: unprocessed data left on queue

### ISSUE THREAD

**Issue by mulyoved** [stoqey/ib#122] opened 2021-11-02 11:34 UTC
After submitting complex order with "hedgeType": "P" I get this error in the log

Decoding error on OPEN_ORDER: unprocessed data left on queue 
```
(["0","None","1.7976931348623157E308","62.0","1.7976931348623157E308","1.7976931348623157E308","1.7976931348623157E308","1.7976931348623157E308","0","","","","0","0","0","0","0",null]).

Please report to https://github.com/stoqey/ib 
- code: 505 - reqId: -1 Error: Decoding error on OPEN_ORDER: unprocessed data left on queue 
(["0","None","1.7976931348623157E308","62.0","1.7976931348623157E308","1.7976931348623157E308","1.7976931348623157E308","1.7976931348623157E308","0","","","","0","0","0","0","0",null]). 
Please report to https://github.com/stoqey/ib
```

This is the order submitted:

```
[
  {
    "order": {
      "action": "BUY",
      "tif": "GTC",
      "orderType": "LMT",
      "totalQuantity": 1,
      "lmtPrice": 73.5,
      "auxPrice": 0,
      "transmit": false,
      "conditions": [
        {
          "time": "20211107 11:11:00",
          "isMore": true,
          "conjunctionConnection": "o",
          "type": 3
        }
      ],
      "conditionsCancelOrder": true,
      "conditionsIgnoreRth": false,
      "orderId": 92
    },
    "contract": {
      "symbol": "ES",
      "secType": "FOP",
      "lastTradeDateOrContractMonth": "20211217 08:30 CST",
      "strike": 4630,
      "right": "C",
      "exchange": "GLOBEX",
      "currency": "USD",
      "localSymbol": "ESZ1 C4630",
      "tradingClass": "ES",
      "multiplier": 50
    }
  },
  {
    "order": {
      "action": "SELL",
      "orderType": "MKT",
      "tif": "GTC",
      "totalQuantity": 0,
      "transmit": false,
      "conditionsCancelOrder": false,
      "conditionsIgnoreRth": false,
      "hedgeType": "P",
      "hedgeParam": "1",
      "conditions": [
        {
          "price": 4628.5,
          "triggerMethod": 0,
          "conId": 446091461,
          "exchange": "GLOBEX",
          "isMore": true,
          "conjunctionConnection": "a",
          "type": 1
        },
        {
          "price": 110.25,
          "triggerMethod": 1,
          "conId": 497082427,
          "exchange": "GLOBEX",
          "isMore": true,
          "conjunctionConnection": "a",
          "type": 1
        }
      ],
      "orderId": 93,
      "parentId": 92
    },
    "contract": {
      "symbol": "ES",
      "secType": "FOP",
      "lastTradeDateOrContractMonth": "20211217 08:30 CST",
      "strike": 4650,
      "right": "C",
      "exchange": "GLOBEX",
      "currency": "USD",
      "localSymbol": "ESZ1 C4650",
      "tradingClass": "ES",
      "multiplier": 50,
      "primaryExch": ""
    }
  },
  {
    "order": {
      "action": "SELL",
      "orderType": "MKT",
      "tif": "GTC",
      "totalQuantity": 1,
      "conditions": [
        {
          "time": "20211212 11:11:00",
          "isMore": true,
          "conjunctionConnection": "o",
          "type": 3
        }
      ],
      "transmit": false,
      "conditionsCancelOrder": false,
      "conditionsIgnoreRth": false,
      "orderId": 94,
      "parentId": 92
    },
    "contract": {
      "symbol": "ES",
      "secType": "FOP",
      "lastTradeDateOrContractMonth": "20211217 08:30 CST",
      "strike": 4630,
      "right": "C",
      "exchange": "GLOBEX",
      "currency": "USD",
      "localSymbol": "ESZ1 C4630",
      "tradingClass": "ES",
      "multiplier": 50
    }
  }
]

```

**Comment by Tsopic** [comment] 2021-11-02 12:10
Seems it's so complex that it's not implemented yet.

Feel free to create PR to fix that.

**Comment by mfrener** [comment] 2021-11-02 12:23
Wondering what we miss there, do you have an idea already?
There seems to be quite a lot of data left on queue, also the "62.0" field that is part of it, is not part of any submitted order. 
So wondering what this.. will have a look at as soon as I have  time ;)

**Comment by mfrener** [comment] 2021-11-05 12:37
Any way you can isolated that issue an some sort of standonline app and attach it here?
Have tried to reproduce it, but haven reached reqAllOpenOrders call yet - I already fail on placing the first order:

```
    const order1 = {
      action: "BUY",
      tif: "GTC",
      orderType: "LMT",
      totalQuantity: 1,
      lmtPrice: 73.5,
      auxPrice: 0,
      transmit: false,
      conditions: [
        {
          time: "20211107 11:11:00",
          isMore: true,
          conjunctionConnection: "o",
          type: 3,
        },
      ],
      conditionsCancelOrder: true,
      conditionsIgnoreRth: false,
      orderId: 92,
    };

    const contract1 = {
      symbol: "ES",
      secType: "FOP",
      lastTradeDateOrContractMonth: "20211217 08:30 CST",
      strike: 4630,
      right: "C",
      exchange: "GLOBEX",
      currency: "USD",
      localSymbol: "ESZ1 C4630",
      tradingClass: "ES",
      multiplier: 50,
    };

    this.api.error.subscribe({
      next: (error) => {
        this.printText(error.error.message);
      },
    });

    this.api.placeOrder(order1.orderId, contract1 as Contract, order1 as Order);
```
==> "Error reading request.Message id 92.  The value you have entered null is invalid.-"
No idea what means, would need to spend more time on setting this up first before I can look at the OPEN_ORDER issue.
So if you can isolate that issue into a piece of code I run, it would be very helpful ;)

**Comment by electic** [comment] 2022-02-19 01:29
Also getting the same error:

```
:: ERR :: Error: Decoding error on OPEN_ORDER: unprocessed data left on queue (["","","0","1","0","0","1",null]). Please report to https://github.com/stoqey/ib - code: 505 - reqId: -1
```

The only change I did was use 3rd party algos. Any advice on where to look and I can debug from there?

**Comment by electic** [comment] 2022-02-19 06:26
Ok, I had some time to debug this tonight. I have the raw dataQueue if that helps. The steps to reproduce.

1. After regular session market close, put in an order with a 3rd party algo with the following parameters: 

```
   {
        exchange: "CSFBALGO",
        algo: "CROSSFINDER+",
        tags: {
            "ExecStyle": 'Normal',
            "DisplaySize": "100",
            "Blockfinder": "0"
        },
    },
```

2. Submit the order.  You will get a warning in the logs that the order will be placed in the following session with a date. Here is the fix dataQueue:

```
[
  '19',
  '172520988',
  'XRTK',
  'STK',
  '',
  '0',
  '?',
  '',
  'CSFBALGO',
  'USD',
  'XRTK',
  'NMS',
  'SELL',
  '300',
  'LMT',
  '3.95',
  '0.0',
  'DAY',
  '',
  'UXXXXXXXX',
  '',
  '0',
  '',
  '0',
  '236990421',
  '0',
  '0',
  '0',
  '',
  '236990421.0/UXXXXXXXX/100',
  '',
  '',
  '',
  '',
  '',
  '',
  '0',
  '',
  '',
  '0',
  '',
  '-1',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '0',
  '0',
  '0',
  '',
  '3',
  '0',
  '0',
  '',
  '0',
  '0',
  '',
  '0',
  'None',
  '',
  '0',
  '',
  '',
  '',
  '?',
  '0',
  '0',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '0',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '0',
  '',
  'IB',
  '0',
  '0',
  'CROSSFINDER+',
  '3',
  'Blockfinder',
  '0',
  'ExecStyle',
  'Normal',
  'DisplaySize',
  '100',
  '0',
  '0',
  'PreSubmitted',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '',
  '',
  '',
  '',
  '',
  '0',
  '0',
  '0',
  'None',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '1.7976931348623157E308',
  '0',
  '',
  '',
  '',
  '0',
  '1',
  '0',
  '0',
  '1',
  undefined
]
```

**Comment by mfrener** [comment] 2022-02-19 18:37
The for the dataQueue dump, help a lot (so we can debug step).
I found one issue that will cause a crash (on PR) but it haven't found the actual problem yet.
The root cause is that we miss to read a token (most likely) and so everything goes out-of-sync and lot of data is left on queue after decoding funtions is done.
I added a detailed description how you can debug on your own, have been trying to find it for the last 2h but no luck
https://github.com/stoqey/ib/pull/145

Feel free if you want to have a try ;)
(I shifted focus to other brokers on my private project, so motivation not that high anymore to work on IB stuff and would be cool if have some guys know how the "core" of this lib works ;) :P )

>  I know you are on another brokerage, but I do not have access to the latest TW-API java files
You can get it there https://interactivebrokers.github.io/#
However "stable" still  API 9.76 (same as we have on repo here), 10.14 only seems to add stuff not change anything. Also don't think the java code is wrong. It's more likely code does something different.

**Comment by mfrener** [comment] 2022-02-20 10:25
Finally fixed with https://github.com/stoqey/ib/pull/145

**Closed by mfrener** 2022-02-20 10:25 UTC
