### ISSUE TITLE
IB test papertrading account for CI

### ISSUE THREAD

**Issue by Tsopic** [stoqey/ib#48] opened 2021-02-19 20:51 UTC
Interactive Brokers used to have demo accounts but now it's more difficult to obtain a PaperTrading account.

I'm looking into ways to make CI work with tests, and need an IB paper trading account to use in CircleCI.

Anyone, having good connections with IB staff?

**Comment by mfrener** [comment] 2021-02-19 21:03
Don't think we will get any help from IB on that. Might be worth a try simply asking them if it possible to create persistent paper account for automated testing purpose. My introducing brokes (CapTrader in Germany) is usually coopreative open it comes to creating additional accounts or logins. Idk how it is with IB guys directly.

Next thing would to post  on twsapi@groups.io (if you don't have an account I can do).
Maybe there are others that have same issue and solved it already (be able to CI-test your stuff against real IB servers).

**Comment by Tsopic** [comment] 2021-02-19 21:07
I don't have an account, please check with them. 

I'll prepare CI config meanwhile

**Comment by mfrener** [comment] 2021-02-19 21:54
https://groups.io/g/twsapi/topic/ci_testing_anyone/80766946?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,80766946

**Comment by mfrener** [comment] 2021-02-20 10:51
So up to now there was no real usefull answer on the mailing group.
Recommendation basically is to build a TWS simulator and test our stack against that.
We coud do that in theory, as we don't need to test real trading scenarios (we don't need acutal exchange, market data ect. logic, just return mock data for testing). We have encoder / decoder code, so also doing the other side not that much anymore.
But...... we will test our code against our code. If we have bug on encoder, it like we have same bug on TWS simulator and test succeeds while it fails with real TWS.- And ofc it is efforts to implement and mainta this.. no idk if it is a good idea to start implementing a TWS simulator.

**Comment by bayareacoder** [comment] 2021-02-20 22:44
@Tsopic Per the IBKR website: "Once your regular trading account has been approved and funded, you are eligible to open a Paper Trading Account.". Just trying to understand what the issue is for you with getting a paper trading account? I got one right away when I opened my live account. Why would simulation be a better route - besides the time spent on it, the IBKR API is very extensive and tricky with the TCP sockets.

**Comment by mfrener** [comment] 2021-02-20 22:59
@bayareacoder paper trading account is fine for local testing, but want it on the CI (continuous integration) pipeline.
Means, every time a dev pushes a change, a pool (ideally :D ) of servers starts to pull up docker containers and test new code against all kind of environment (i.e. you want to test against a set of different TWS versions at least, having different account types would be cool (Single, IRA, Advisor, .. they have different features enabled), or different configs on the accounts to i.e. test trade restricton errors, ....).
You could do this with a single account, all serial, but a CI-cycle will than probably take 24h. Also you need a paper trading account that be used - I need mine for myself  =)

**Comment by bayareacoder** [comment] 2021-02-20 23:12
@mfrener Seems several have been successful at running IB Gateway in a Docker container and automating the login. e.g. https://github.com/th3sys/capsule, which uses https://github.com/ib-controller/ib-controller.

**Comment by mfrener** [comment] 2021-02-20 23:18
@bayareacoder yeah, that's not the issue @Tsopic has setup this already and integrate in on CI. But you need to enter account credentials to ib-contoller. I need my paper account for local testing, Tspoic as well. Can we use your one? You need to re-create every month because it expires and update the CI script. Also pls ask some of your friends to sponsor their account, because we would like to run the dockers (there will one for each TWS versoin we support, hopefully) in parallel not in serial. You see the problem ;)

**Comment by bayareacoder** [comment] 2021-02-20 23:25
OK so the issue is that you just need more paper trading accounts. It seems to me getting a few if your family members to put minimum funds to open live accounts so you can get extra paper accounts will be a lot easier than building a simulator. 
And no you can't use my account :) Best of luck.

**Comment by mfrener** [comment] 2021-02-20 23:30
Yes, a simulator is out of question. We build an API client here, a sim that would be a whole new project.
Think I'm going to wait for next week until the some weekend party folks catches up on twsapi@groups.io and if there is nothing usefull, I will ask at my broker.. maybe can get some special deal like 5 free paper accounts for posting their logo on the readme or whatever.

**Comment by mfrener** [comment] 2021-07-29 22:45
Closed as no broker seems to be willing to sponsor some accounts.

**Closed by mfrener** 2021-07-29 22:45 UTC
