### ISSUE TITLE
Error: Decoding error on undefined: unprocessed data left on queue 

### ISSUE THREAD

**Issue by ramon1911** [stoqey/ib#182] opened 2023-07-27 06:55 UTC
Hello, I'd just received this error while using the API:
Error: Decoding error on undefined: unprocessed data left on queue (["20230727 02:49:21 EST",null]). Please report to https://github.com/stoqey/ib 505
It says to report it, so I am making this issue thread, feel free to close.
To get this error, I am using the reqMatchingSymbols method on IBApi. In particular, I am using React to take a text input, and whenver the user types, then sending this request using your library to IB, and getting the response. Furthermore, I am using both the ib.connect and ib.disconnect method every time the user types a single character in the react field, and the data itself is passed through electron IPC, so there is a lot of friction.Therefore, this error is most likely due to a very large amount of requests in a short amount of time, as I'm getting a couple other errors such as "Error: No parser implementation found for token: undefined (166). 505". If you would like to see the code, please let me know. Thank you for your time.

**Comment by rylorin** [comment] 2023-07-29 07:10
Hello,
thanks for reporting.
Can you tell us what parameters values for `reqMatchingSymbols` are raising this error?
This info would help to reproduce and investigate.
Thanks

**Comment by ramon1911** [comment] 2023-07-31 08:40
> Hello, thanks for reporting. Can you tell us what parameters values for `reqMatchingSymbols` are raising this error? This info would help to reproduce and investigate. Thanks

Certainly. I used ib.once(EventName.nextValidId) to obtain the orderId, which I passed as the first input for reqMatching symbols, and for the second parameter I used a string, usually something like "aa" or "tsl", anything that would be the beginning of a ticker symbol.

However, it is worth it to note that I implemented a delay of 0.5ms between each reqMatchingSymbols request, and this had completely solved any errors I had using the API. Hope this helps.

**Comment by rylorin** [comment] 2023-09-19 18:58
Hello,
I created a new unit test to try to reproduce your bug: `src/tests/unit/api/matching-symbols.test.ts`
Where I call `reqMatchingSymbols` 3 times with connection/disconnection each time but I didn't get your bug.
If you have some time to edit the test to show up the problem, we could investigate.
Thanks

**Comment by rylorin** [comment] 2024-11-23 08:03
Hello,
I close this issue because:
- no more activity for 1 year
- I fixed a bug with connection setup code that have probably solved this issue
Feel free to revert back if the issue is still alive

**Closed by rylorin** 2024-11-23 08:03 UTC
